#' Create Significant Taxa Table from DESeq2 Results
#'
#' This function processes DESeq2 results to generate a table of significant taxa
#' based on specified p-value and log2 fold change thresholds, incorporating
#' taxonomic annotations from a phyloseq object.
#'
#' @param ps_obj A phyloseq object containing taxonomic information.
#' @param diagdds A DESeq2 results object generated by \code{DESeq2::results()}.
#' @param contrast A character vector specifying the contrast for comparison.
#'   Should follow DESeq2 contrast specification format.
#' @param alpha Numeric, significance threshold for adjusted p-values.
#'   Default: 0.05.
#' @param minlfc Numeric, minimum absolute log2 fold change threshold.
#'   Default: 1.
#' @param maxlfc Numeric, maximum absolute log2 fold change threshold.
#'   Default: 20.
#'
#' @return A data frame containing significant taxa with the following columns:
#' \itemize{
#'   \item DESeq2 results columns (baseMean, log2FoldChange, pvalue, padj)
#'   \item Taxonomic annotations from phyloseq object
#'   \item signif (significance stars)
#'   \item group (contrast group based on LFC direction)
#'   \item model (always 'deseq2')
#'   \item value (contrast value)
#'   \item coef (log2 fold change values)
#' }
#' Returns NULL if no significant taxa found.
#'
#' @examples
#' \dontrun{
#' # Example using phyloseq and DESeq2 objects
#' contrast <- c("Condition", "Treatment", "Control")
#' sigtab <- create_sigtab(ps_obj = phyloseq_object,
#'                         diagdds = deseq_results,
#'                         contrast = contrast)
#' }
#'
#' @importFrom DESeq2 results
#' @importFrom phyloseq tax_table
#' @importFrom dplyr mutate case_when
#' @export
create_sigtab <- function(ps_obj, diagdds, contrast, alpha = 0.05, minlfc = 1, maxlfc = 20) {
  # Get DESeq2 results
  res <- DESeq2::results(
    diagdds,
    contrast = contrast,
    cooksCutoff = FALSE,
    independentFiltering = FALSE
  )

  # Check for valid results
  if (all(is.na(res$pvalue))) {
    warning(paste("No results for contrast:", paste(contrast, collapse = " vs ")))
    return(NULL)
  }

  # Filter significant results
  sigtab <- res[
    which(!is.na(res$pvalue) &
            abs(res$log2FoldChange) >= minlfc & !is.na(res$log2FoldChange) &
            abs(res$log2FoldChange) <= maxlfc &
            res$padj <= alpha),
  ]

  if (nrow(sigtab) == 0) {
    message(paste("No significant taxa found for contrast:",
                  paste0(contrast, collapse = "_")))
    return(NULL)
  }

  # Add taxonomic information
  sigtab <- cbind(
    as.data.frame(sigtab),
    as(phyloseq::tax_table(ps_obj)[rownames(sigtab), ], "matrix")
  )

  # Create significance labels
  sigtab$signif <- ifelse(
    sigtab$padj <= 0.001, "***",
    ifelse(
      sigtab$padj <= 0.01, "**",
      ifelse(sigtab$padj <= 0.05, "*", "")
    )
  )

  # Sort and format results
  sigtab <- sigtab[order(sigtab$log2FoldChange), ]
  asv_sigtab <- as.data.frame(sigtab)
  asv_sigtab$comparison <- paste0(contrast[2], "_", contrast[3])
  asv_sigtab$group1 <- contrast[2]
  asv_sigtab$group2 <- contrast[3]

  asv_sigtab <- asv_sigtab %>%
    dplyr::mutate(
      group = dplyr::case_when(
        log2FoldChange > 0 ~ contrast[2],
        log2FoldChange < 0 ~ contrast[3],
        TRUE ~ NA_character_
      ),
      model = "deseq2",
      value = contrast[2],
      coef = as.numeric(log2FoldChange)
    ) %>%
    tibble::rownames_to_column("Taxon")
  print(asv_sigtab)

  return(asv_sigtab)
}

#' Calculate Abundance Statistics for Taxonomic Features
#'
#' This function calculates relative abundance and prevalence statistics for specified taxa
#' across sample groups in a phyloseq object.
#'
#' @param ps_obj A phyloseq object containing OTU table and sample data
#' @param taxa_names Character vector of taxonomic features (OTUs/ASVs) to analyze
#' @param group_var Character string specifying the grouping variable in sample data
#'
#' @return A long-format data.frame with columns:
#' \itemize{
#'   \item Taxon - Taxonomic feature identifier
#'   \item Sample - Sample identifier
#'   \item Abundance - Relative abundance (compositional)
#'   \item group_var - Group assignment for each sample
#' }
#'
#' @examples
#' \dontrun{
#' data(GlobalPatterns)
#' taxa <- c("OTU1", "OTU2", "OTU3")
#' stats <- calculate_abundance_stats(GlobalPatterns, taxa, "SampleType")
#' }
#'
#' @importFrom phyloseq otu_table sample_data
#' @importFrom microbiome transform
#' @importFrom dplyr select left_join
#' @importFrom tibble rownames_to_column
#' @importFrom tidyr pivot_longer
#' @export
calculate_abundance_stats <- function(ps_obj, taxa_names, group_var = "bmi_group") {
  # Input validation
  if (!inherits(ps_obj, "phyloseq")) {
    stop("ps_obj must be a phyloseq object")
  }

  if (!group_var %in% colnames(phyloseq::sample_data(ps_obj))) {
    stop(paste("Group variable", group_var, "not found in sample data"))
  }

  # Transform to compositional data
  ps_obj_comp <- microbiome::transform(ps_obj, transform = "compositional")

  # Extract data
  otu_table <- as.data.frame(phyloseq::otu_table(ps_obj_comp))
  sample_data <- as(phyloseq::sample_data(ps_obj_comp),'data.frame')

  # Check taxa names
  if (length(taxa_names) == 0) {
    return(NULL)
  }
  missing_names <- dplyr::setdiff(taxa_names, colnames(otu_table))
  if (length(missing_names) > 0) {
    warning("The following names are missing:", paste(missing_names, collapse = ", "))
  }

  # Filter OTU table
  otu_table <- otu_table %>%
    dplyr::select(any_of(taxa_names))

  # Convert to long format
  melted_abundance <- t(otu_table) %>%
    as.data.frame() %>%
    tibble::rownames_to_column("Taxon") %>%
    tidyr::pivot_longer(
      cols = -"Taxon",
      names_to = "Sample",
      values_to = "Abundance"
    )

  # Add group information
  melted_abundance <- melted_abundance %>%
    dplyr::left_join(
      sample_data %>%
        tibble::rownames_to_column("Sample") %>%
        dplyr::select("Sample", !!group_var),
      by = "Sample"
    )

  return(melted_abundance)
}

#' Create Comparison Plots for Differential Abundance Results
#'
#' Generates a set of three plots (log2FC barplot, abundance violin plot, prevalence barplot)
#' for a single comparison from DESeq2 results.
#'
#' @param data Data.frame containing DESeq2 results (must contain log2FoldChange, Species, etc.)
#' @param comparison_name Character string specifying the comparison (e.g., "Lean vs Obesity")
#' @param size Numeric, base font size for plots (default: 12)
#' @param group_var_fold_change Character string specifying the grouping variable
#' for log2FC barplot (default: "Phylum")
#' @param group_var_abund_prev Character string specifying the grouping variable
#' for abundance violin plot and prevalence barplot (default: "bmi_group")
#' @param ps_obj Phyloseq object for abundance data (required)
#' @param group_colors Named vector of colors for groups (optional)
#'
#' @return A ggplot object containing the combined visualization
#'
#' @examples
#' \dontrun{
#' plots <- create_comparison_plots(
#'   data = deseq_results,
#'   comparison_name = "Lean vs Obesity",
#'   ps_obj = phyloseq_object
#' )
#' }
#'
#' @importFrom ggplot2 ggplot aes geom_col geom_text scale_fill_manual coord_flip labs
#' @importFrom ggplot2 theme_minimal theme element_text geom_boxplot scale_y_continuous
#' @importFrom dplyr filter mutate group_by summarise left_join
#' @importFrom tibble rownames_to_column
#' @importFrom scales percent_format
#' @importFrom ggpubr ggarrange
#' @export
create_comparison_barplot <- function(data,
                                    comparison_name,
                                    size = 12,
                                    group_var_fold_change = "Phylum",
                                    group_var_abund_prev = "bmi_group",
                                    ps_obj,
                                    group_colors_fold_change = NULL,
                                    group_colors_abund_prev = NULL) {
  # Input validation
  if (!inherits(data, "data.frame")) {
    stop("data must be a data.frame")
  }

  if (!inherits(ps_obj, "phyloseq")) {
    stop("ps_obj must be a phyloseq object")
  }

  required_cols <- c("comparison", "log2FoldChange", "Species", "group", "signif","Phylum")
  if (!all(required_cols %in% colnames(data))) {
    stop(paste("data must contain columns:", paste(required_cols, collapse = ", ")))
  }

  # Filter data for current comparison
  plot_data <- data %>% dplyr::filter(.data$comparison == comparison_name)
  if (nrow(plot_data) == 0) {
    message(paste("No data found for comparison:", comparison_name))
    return(NULL)
  }


  # Get abundance data
  abundance_data <- calculate_abundance_stats(
    ps_obj = ps_obj,
    taxa_names = plot_data$Taxon,
    group_var = group_var_abund_prev
  )

  if (is.null(abundance_data)) {
    warning(paste("No abundance data available for comparison:", comparison_name))
    return(NULL)
  }

  # Extract comparison groups
  groups <- unlist(strsplit(comparison_name, "_"))
  if (length(groups) != 2) {
    stop("comparison_name must be in format 'Group1_Group2'")
  }

  group_1 <- groups[1]
  group_2 <- groups[2]

  # Filter abundance data for comparison groups
  plot_data_full <- abundance_data %>%
    dplyr::filter(!!sym(group_var_abund_prev) %in% c(group_1, group_2)) %>%
    dplyr::left_join(
      plot_data,
      by = "Taxon"
    )

  if (is.null(group_colors_fold_change)) {
    unique_phyla <- unique(plot_data$Phylum)
    group_colors_fold_change <- scales::hue_pal()(length(unique_phyla))
    names(group_colors_fold_change) <- unique_phyla
  }

  if (is.null(group_colors_abund_prev)) {
    unique_groups <- unique(plot_data_full[[group_var_abund_prev]])
    group_colors_abund_prev <- scales::hue_pal()(length(unique_groups))
    names(group_colors_abund_prev) <- unique_groups
  }

  # 1. Log2FC barplot
  p1 <- ggplot2::ggplot(plot_data,
                        ggplot2::aes(x = reorder(.data$Species, .data$log2FoldChange),
                                     y = .data$log2FoldChange,
                                     fill = .data$Phylum))  +
    ggplot2::geom_col(width = 0.7) +
    ggplot2::geom_text(
      ggplot2::aes(label = .data$signif),
      vjust = 0.5,
      hjust = ifelse(plot_data$log2FoldChange > 0, -0.2, 1.2),
      size = 3
    ) +
    ggplot2::scale_fill_manual(values = group_colors_fold_change) +
    ggplot2::scale_color_manual(values = group_colors_fold_change) +
    ggplot2::coord_flip() +
    ggplot2::labs(x = "Species", y = "log2 fold change") +
    ggplot2::theme_bw() +
    ggplot2::theme(
      axis.text.y = ggplot2::element_text(size = size, face = 'italic'),
      plot.title = ggplot2::element_text(size = size + 2),
      axis.text.x = ggplot2::element_text(size = size),
      legend.position = "top"  # Убираем легенду для цветов стрелок
    )

  # 2. Abundance boxplot
  p2 <- ggplot2::ggplot(plot_data_full,
                        ggplot2::aes(x = reorder(.data$Species, plot_data$log2FoldChange[match(.data$Species, plot_data$Species)]),
                                     y = log10(.data$Abundance + 0.00001),
                                     fill = !!sym(group_var_abund_prev))) +
    #ggplot2::geom_violin() +
    ggplot2::geom_boxplot(outlier.colour = "gray", outlier.shape = 1,alpha = 1) +
    ggplot2::scale_fill_manual(values = group_colors_abund_prev) +
    ggplot2::coord_flip() +
    ggplot2::labs(x = "Species", y = "log10(Relative Abundance + 0.00001)") +
    ggplot2::theme_bw() +
    ggplot2::theme(
      axis.text.y = ggplot2::element_blank(),
      axis.title.y = ggplot2::element_blank(),
      axis.text.x = ggplot2::element_text(size = size),
      legend.position = "none"
    )

  # 3. Prevalence barplot
  prevalence_df <- plot_data_full %>%
    dplyr::group_by(.data$Species, !!sym(group_var_abund_prev)) %>%
    dplyr::summarise(
      Prevalence = sum(.data$Abundance > 0) / dplyr::n(),
      .groups = "drop"
    )

  p3 <- ggplot2::ggplot(prevalence_df,
                        ggplot2::aes(x = reorder(.data$Species, plot_data$log2FoldChange[match(.data$Species, plot_data$Species)]),
                                     y = .data$Prevalence * 100,
                                     fill = !!sym(group_var_abund_prev))) +
    ggplot2::geom_col(position = "dodge") +
    ggplot2::scale_fill_manual(values = group_colors_abund_prev) +
    ggplot2::scale_y_continuous(labels = scales::percent_format(scale = 1)) +
    ggplot2::coord_flip() +
    ggplot2::labs(x = "Species", y = "Prevalence (%)") +
    ggplot2::theme_bw() +
    ggplot2::theme(
      axis.text.y = ggplot2::element_blank(),
      axis.title.y = ggplot2::element_blank(),
      axis.text.x = ggplot2::element_text(size = size),
      legend.position = "none"
    )

  p1 <- p1 + scale_fill_manual(name = group_var_fold_change, values = group_colors_fold_change)
  p2 <- p2 + scale_fill_manual(name = group_var_abund_prev, values = group_colors_abund_prev)
  p3 <- p3 + scale_fill_manual(name = group_var_abund_prev, values = group_colors_abund_prev)
  # Combine plots
  combined_plot <- ggpubr::ggarrange(
    p1 ,p2, p3,
    common.legend = FALSE,
    legend = "top",align = 'h',
    nrow = 1,
    widths = c(2, 1, 1)
  ) +
    ggplot2::labs(title = comparison_name) +
    theme(
      plot.title = element_text(face = "bold", margin = ggplot2::margin(10, 0, 10, 0), size = 14),
      legend.title = element_text(size = 12, face = "bold")
    )

  return(list(prevalence_df,combined_plot,plot_data_full))
}
#' Create Comparative Heatmap with Abundance and Prevalence Annotations
#'
#' Generates a complex heatmap comparing coefficients from different models with
#' abundance and prevalence annotations. The function handles data from DESeq2 and
#' Maaslin2, ensures consistent effect directions, and provides customizable
#' visualizations.
#'
#' @param data_deseq Dataframe containing DESeq2 results (must include Taxon, coef,
#' model, padj, signif columns).
#' @param data_maaslin Dataframe containing Maaslin2 results (same structure as data_deseq).
#' @param ref_group Character string specifying the reference group.
#' @param comp_group Character string specifying the comparison group.
#' @param taxa_level Character string specifying the taxonomic level to analyze (e.g., "Species").
#' @param ps_obj Phyloseq object containing microbial abundance data.
#' @param group_var_abund_prev Character string specifying grouping variable for abundance/prevalence plots.
#' @param comparison_name Character string for plot title.
#' @param group_colors_abund_prev Named vector of colors for groups (optional).
#' @param color_low Hex color for negative coefficients (default: "#45CAFF").
#' @param color_mid Hex color for zero coefficients (default: "white").
#' @param color_high Hex color for positive coefficients (default: "#DE3163").
#' @param text_size Base text size for plots (default: 9).
#' @param pvalue_digits Number of digits for p-value formatting (default: 2).
#' @param heatmap_height Height of heatmap in cm (default: 10).
#' @param heatmap_width Width of heatmap in cm (default: 7).
#' @param number_model_true Threshold for minimum non-zero models required per taxon (default: 2).
#'
#' @return A list containing:
#' \itemize{
#'   \item heatmap_plot - Combined plot as ggplot object
#'   \item heatmap_obj - Raw ComplexHeatmap object for further customization
#' }
#'
#' @examples
#' \dontrun{
#' result <- create_comparison_heatmap(
#'   data_deseq = deseq_results,
#'   data_maaslin = maaslin_results,
#'   ref_group = "Control",
#'   comp_group = "Treatment",
#'   taxa_level = "Species",
#'   ps_obj = phyloseq_data,
#'   group_var_abund_prev = "Group",
#'   comparison_name = "Control vs Treatment"
#' )
#' print(result[[1]])  # Display the plot
#' }
#'
#' @importFrom ComplexHeatmap Heatmap draw anno_barplot rowAnnotation
#' @importFrom circlize colorRamp2
#' @importFrom grid grid.grabExpr gpar grid.text unit
#' @importFrom cowplot plot_grid
#' @importFrom ggplot2 ggplot aes geom_boxplot scale_fill_manual coord_flip labs
#' theme_bw theme element_text element_blank
#' @importFrom dplyr select mutate filter group_by summarise case_when all_of sym
#' @importFrom tidyr pivot_wider
#' @importFrom tibble column_to_rownames
#' @importFrom scales hue_pal percent_format
#' @importFrom phyloseq taxa_names
#' @export
create_comparison_heatmap <- function(data_deseq,
                                      data_maaslin,
                                      ref_group,
                                      comp_group,
                                      taxa_level,
                                      ps_obj,
                                      group_var_abund_prev,
                                      comparison_name,
                                      group_colors_abund_prev = NULL,
                                      color_low = "#45CAFF",
                                      color_mid = "white",
                                      color_high = "#DE3163",
                                      text_size = 9,
                                      pvalue_digits = 2,
                                      heatmap_height = 10,
                                      heatmap_width = 7,
                                      number_model_true = 2
                                      ) {
  if (missing(data_deseq) || missing(data_maaslin) || missing(ref_group) ||
      missing(comp_group) || missing(taxa_level) || missing(ps_obj) ||
      missing(group_var_abund_prev) || missing(comparison_name)) {
    stop("Required arguments are missing")
  }
  data_deseq_filtered <- data_deseq %>%
    dplyr::filter(comparison == comparison_name)
  data_maaslin_filtered <- data_maaslin %>%
    dplyr::filter(comparison == comparison_name)

  # Data Preparation and Direction Consistency ----
  final_df <- rbind(data_deseq_filtered, data_maaslin_filtered)

  final_df_clean <- final_df %>%
    dplyr::mutate(
      coef = dplyr::case_when(
        reference_group == ref_group & comparison_group == comp_group ~ coef,
        reference_group == comp_group & comparison_group == ref_group ~ -coef,
        TRUE ~ coef
      ),
      reference_group = ref_group,
      comparison_group = comp_group
    )


  # Create Coefficient Matrix ----
  coef_matrix <- final_df_clean %>%
    dplyr::select(dplyr::all_of(taxa_level), model, coef) %>%
    tidyr::pivot_wider(names_from = model, values_from = coef) %>%
    tibble::column_to_rownames(taxa_level) %>%
    as.matrix()

  coef_matrix[is.na(coef_matrix)] <- 0
  #zero_counts <- apply(coef_matrix, 1, function(x) sum(x == 0, na.rm = TRUE))

  if (number_model_true == 0) {
    # Only keep rows with ALL non-zero values
    coef_matrix <- coef_matrix[rowSums(coef_matrix != 0) == ncol(coef_matrix), , drop = FALSE]
  } else {
    # Original logic for other cases
    zero_counts <- rowSums(coef_matrix == 0, na.rm = TRUE)
    coef_matrix <- coef_matrix[zero_counts <= number_model_true, , drop = FALSE]
  }

  if (nrow(coef_matrix) == 0) {
    stop("No taxa passed the filtering criteria. Adjust number_model_true or check your data.")
  }

  row_means <- rowMeans(coef_matrix, na.rm = TRUE)
  taxa_order <- names(sort(row_means, decreasing = TRUE))
  coef_matrix <- coef_matrix[taxa_order, , drop = FALSE]
  # Create Annotation Matrix ----
  annotation_matrix <- final_df_clean %>%
    dplyr::mutate(
      formatted_padj = ifelse(
        padj < 0.001,
        "<0.001",
        format.pval(padj, digits = pvalue_digits, eps = 0.001)
      ),
      cell_text = sprintf(
        "%.2f
        %s
        (p = %s)",  # Replaced \t with spaces
        coef,
        signif,
        formatted_padj
      )
    ) %>%
    dplyr::select(dplyr::all_of(taxa_level), model, cell_text) %>%
    tidyr::pivot_wider(names_from = model, values_from = cell_text) %>%
    tibble::column_to_rownames(taxa_level) %>%
    as.matrix()
  annotation_matrix <- annotation_matrix[taxa_order, , drop = FALSE]

  phyloseq::taxa_names(ps_obj) <- ps_obj@tax_table[,taxa_level]
  # Abundance and Prevalence Calculations ----
  abundance_data <- calculate_abundance_stats(
    ps_obj = ps_obj,
    taxa_names = final_df_clean[[taxa_level]],
    group_var = group_var_abund_prev
  )

  plot_data_full <- abundance_data %>%
    dplyr::filter(!!dplyr::sym(group_var_abund_prev) %in% c(ref_group, comp_group)) %>%
    dplyr::mutate(Taxon = factor(Taxon, levels = taxa_order))

  # Create Visualization Components ----
  if (is.null(group_colors_abund_prev)) {
    unique_groups <- unique(plot_data_full[[group_var_abund_prev]])
    group_colors_abund_prev <- scales::hue_pal()(length(unique_groups))
    names(group_colors_abund_prev) <- unique_groups
  }
  annotation_colors <- group_colors_abund_prev[c(ref_group, comp_group)]

  plot_data_full <- abundance_data %>%
    dplyr::filter(!!dplyr::sym(group_var_abund_prev) %in% c(ref_group, comp_group)) %>%
    dplyr::mutate(Taxon = factor(Taxon, levels = taxa_order))

  abund_data <- plot_data_full %>%
    dplyr::filter(!is.na(Taxon)) %>%
    dplyr::mutate(Abundance = log10(.data$Abundance + 0.00001)) %>%
    dplyr::select(Taxon, !!dplyr::sym(group_var_abund_prev), Abundance) %>%
    tidyr::pivot_wider(
      names_from = !!dplyr::sym(group_var_abund_prev),
      values_from = Abundance,
      values_fn = list(Abundance = mean)
    ) %>%
    tibble::column_to_rownames("Taxon") %>%
    as.data.frame()
  abund_data <- abund_data[taxa_order, , drop = FALSE]
  prev_data <- plot_data_full %>%
    dplyr::filter(!is.na(Taxon)) %>%
    dplyr::group_by(Taxon, !!dplyr::sym(group_var_abund_prev)) %>%
    dplyr::summarise(
      Prevalence = sum(.data$Abundance > 0) / dplyr::n(),
      .groups = "drop"
    ) %>%
    tidyr::pivot_wider(
      names_from = !!dplyr::sym(group_var_abund_prev),
      values_from = Prevalence
    ) %>%
    tibble::column_to_rownames("Taxon") %>%
    as.data.frame()
  prev_data <- prev_data[taxa_order, , drop = FALSE]

  # Create Heatmap with annotations ----

  ra <- ComplexHeatmap::rowAnnotation(
    Mean_log10_abundance = ComplexHeatmap::anno_barplot(
      abund_data,
      which = "row",
      width = grid::unit(3, "cm"),
      gp = grid::gpar(fill = annotation_colors),
      axis_param = list(side = "bottom"),beside = TRUE, attach = TRUE
    ),
    Empty= ComplexHeatmap::anno_empty(  # Spacer between annotations
      width = grid::unit(0.5, "cm"),
      which = "row"
    ),
    Prevalence = ComplexHeatmap::anno_barplot(
      prev_data,
      which = "row",
      width = grid::unit(3, "cm"),
      beside = TRUE, attach = TRUE,
      gp = grid::gpar(fill = annotation_colors),
      labels_gp = gpar(fontsize = text_size)
    ),
    show_annotation_name = TRUE,
    annotation_name_rot = 45,
    annotation_name_side = "bottom",
    annotation_name_gp = grid::gpar(fontsize = text_size * 0.8),
    annotation_legend_param = list(
      title = group_var_abund_prev,
      labels = names(annotation_colors),
      legend_gp = gpar(fill = annotation_colors)
    )
  )

  heatmap_obj <- ComplexHeatmap::Heatmap(
    coef_matrix,
    name = "Coef",
    col = circlize::colorRamp2(
      c(min(coef_matrix, na.rm = TRUE), 0, max(coef_matrix, na.rm = TRUE)),
      c(color_low, color_mid, color_high)
    ),
    cell_fun = function(j, i, x, y, width, height, fill) {
      grid::grid.text(
        annotation_matrix[i, j],
        x = x,
        y = y,
        gp = grid::gpar(fontsize = text_size/2, col = "black"),
        just = "centre"
      )
    },
    right_annotation = ra,
    row_names_side = "left",
    row_names_gp = gpar(fontsize = text_size,fontface = "italic",color='black',linewidth = 1.2),
    column_names_rot = 45,
    cluster_rows = FALSE,
    cluster_columns = FALSE,
    show_row_names = TRUE,
    show_column_names = TRUE,
    row_order = rev(taxa_order),
    heatmap_legend_param = list(title = "Effect size",direction = "horizontal"),
    column_title = comparison_name,
    column_title_gp = grid::gpar(fontsize = text_size + 2, fontface = "bold"),
    width = unit(heatmap_width, "cm"),
    height = unit(heatmap_height, "cm"),
  )
  annotation_legend <- Legend(
    title = group_var_abund_prev,
    at = names(annotation_colors),
    legend_gp = gpar(fill = annotation_colors),
    direction = "vertical",
    labels_gp = gpar(fontsize = text_size)
  )

  heatmap_grob <- grid::grid.grabExpr({
    ComplexHeatmap::draw(heatmap_obj,heatmap_legend_side = "top", annotation_legend_side = "top",
                         annotation_legend_list = list(annotation_legend), merge_legend = TRUE)
  })
  heatmap_plot <- cowplot::plot_grid(heatmap_grob)
  return(list(
    heatmap_plot = heatmap_plot,
    heatmap_obj = heatmap_obj
  ))

}
