name: pkgdown

on:
  push:
    branches: [main, master]

jobs:
  pkgdown:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies for R packages
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libssl-dev \
            libfontconfig1-dev \
            libharfbuzz-dev \
            libfribidi-dev

      - name: Install minimal packages for pkgdown
        run: |
          Rscript -e "install.packages(c('pkgdown', 'knitr', 'rmarkdown'), repos = 'https://cloud.r-project.org')"

      - name: Build site without installing package dependencies
        run: |
          Rscript -e "pkgdown::build_site(install = FALSE)"

      - name: Build site
        run: |
          Rscript -e "pkgdown::build_site()"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true
