name: pkgdown

on:
  push:
    branches: [main, master]

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libfontconfig1-dev \
            libharfbuzz-dev \
            libfribidi-dev

      - name: Install pkgdown and basic dependencies
        run: |
          Rscript -e "install.packages(c('remotes', 'knitr', 'rmarkdown'), repos = 'https://cloud.r-project.org')"
          Rscript -e "remotes::install_cran('pkgdown', dependencies = TRUE)"

      - name: Verify installation
        run: |
          Rscript -e "if (!requireNamespace('pkgdown', quietly = TRUE)) { stop('pkgdown not installed') } else { message('✓ pkgdown installed successfully') }"

      - name: Build site (skip dependencies)
        run: |
          Rscript -e "pkgdown::build_site(install = FALSE, new_process = FALSE)"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true
