name: pkgdown

on:
  push:
    branches: [main, master]

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libharfbuzz-dev libfribidi-dev libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev

      - name: Install Bioconductor and CRAN packages
        run: |
          Rscript -e "install.packages('BiocManager', repos = 'https://cloud.r-project.org')"
          Rscript -e "BiocManager::install('phyloseq')"
          Rscript -e "install.packages(c('remotes', 'devtools', 'pkgdown', 'extrafont'), repos = 'https://cloud.r-project.org')"

      - name: Install GitHub packages
        run: |
          Rscript -e "remotes::install_github('david-barnett/microViz')"
          Rscript -e "remotes::install_github('mikemc/speedyseq', dependencies = TRUE)"
          Rscript -e "remotes::install_github('wch/extrafont')"

      - name: Install package dependencies
        run: |
          Rscript -e "devtools::install_deps(dependencies = TRUE)"

      - name: Build site
        run: |
          Rscript -e "pkgdown::build_site()"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true
