name: pkgdown

on:
  push:
    branches: [main, master]

jobs:
  pkgdown:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2

      - name: Install Bioconductor manager
        run: Rscript -e "install.packages('BiocManager', repos = 'https://cloud.r-project.org')"

      - name: Install required packages
        run: |
          Rscript -e "BiocManager::install('phyloseq')"
          Rscript -e "install.packages(c('remotes', 'pkgdown', 'knitr', 'rmarkdown'), repos = 'https://cloud.r-project.org')"
          Rscript -e "remotes::install_github('wch/extrafont')"
          Rscript -e "remotes::install_github('david-barnett/microViz')"
          Rscript -e "remotes::install_github('mikemc/speedyseq', dependencies = TRUE)"

      - name: Install package dependencies using remotes
        run: |
          Rscript -e "remotes::install_deps(dependencies = TRUE)"

      - name: Build site
        run: |
          Rscript -e "pkgdown::build_site()"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true
